### ISSUE TITLE
rokot-auth and other libraries

### ISSUE THREAD

**Issue by ESTrainer** [Rocketmakers/rokot#1]
Is `rokot-auth` still available to public? Looks like we cannot open it anymore? We like `rokot-auth` (unfortunately we have cloned it yet) and wanted to do some more contribution, please let us know whether  you can make them public again.

**Comment by jonnystoten** [comment]
Hi @ESTrainer 

It is indeed still available, we're just in the process of moving Rocketmakers' open-source code to GitLab. You can find rokot-auth here: https://gitlab.com/rocketmakers/rokot/auth. I'll update this repo to make that clear at some point!

Merge requests on GitLab are very welcome! :smile:

**Comment by ESTrainer** [comment]
thanks @jonnystoten

**Comment by ESTrainer** [comment]
Can you share the `rokot-apicontroller` project link as well? I couldn't find it anywhere.

**Comment by jonnystoten** [comment]
All of rokot was accidentally private, sorry about that. You should now be able to find everything at https://gitlab.com/rocketmakers/rokot
